{{- if .Values.ec2NodeClass.enabled }}
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: {{ default (include "karpenter-nodepool.name" .) (.Values.ec2NodeClass.name | trim) | quote }}
  labels:
    {{- include "karpenter-nodepool.labels" . | nindent 4 }}
spec:
  role: {{ .Values.ec2NodeClass.role | quote }}
  {{- with .Values.ec2NodeClass.amiSelectorTerms }}
  amiSelectorTerms:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.ec2NodeClass.subnetSelectorTerms }}
  subnetSelectorTerms:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.ec2NodeClass.securityGroupSelectorTerms }}
  securityGroupSelectorTerms:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.ec2NodeClass.tags }}
  tags:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
