apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-vote
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  source:
    repoURL: https://github.com/KastonI/KubeVote-Pet-Project.git
    targetRevision: master
    path: helm/kube-vote

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true