apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
  namespace: default
spec:
  selector:
    app: vote
  type: NodePort
  # sessionAffinity: None
  # sessionAffinityConfig:
  #   clientIP:
  #     timeoutSeconds: 10800
  ports:
  - name: vote
    protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 30080