apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgresql.primary.persistence.existingClaim }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  {{- if eq .Values.env "local" }}
  storageClassName: {{ .Values.storage.local.storageClassName }}
  volumeName: {{ .Values.storage.local.pv.name }}   # <-- привязка к твоему PV
  {{- else if eq .Values.env "eks" }}
  storageClassName: {{ .Values.storage.eks.storageClass.name }} # <-- динамика через SC
  {{- else }}
  {{- fail (printf "Unknown env=%q (use local|eks)" .Values.env) }}
  {{- end }}
