apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" (include "kube-vote.name" .) .Values.result.name | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "kube-vote.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "kube-vote.selectorLabels" (dict "component" .Values.result.name "Release" .Release "Chart" .Chart "Values" .Values) | nindent 4 }}

  type: {{ .Values.result.service.type }}
  ports:
  - name: {{ .Values.result.name }}
    protocol: TCP
    port: {{ .Values.result.service.port }}
    targetPort: {{ .Values.result.service.targetPort }}
    nodePort: {{ .Values.result.service.nodePort }}