{{- if .Values.vote.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ printf "%s-%s-hpa" (include "kube-vote.name" .) .Values.vote.name | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "kube-vote.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ printf "%s-%s" (include "kube-vote.name" .) .Values.vote.name | trunc 63 | trimSuffix "-" }}
  minReplicas: {{ .Values.vote.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.vote.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.vote.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.vote.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.vote.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.vote.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
